version: '3.8'
services:
  indexer:
    build:
      context: ../../
      dockerfile: docker/ponder/Dockerfile
    ports:
      - "127.0.0.1:42069:42069"
    environment:
      - PONDER_RPC_URL=https://rpc.sketchpad-1.forma.art
      - PONDER_CHAIN_ID=984123
      - PONDER_START_BLOCK=10176490
      - PONDER_DROP_ADDRESS="0x1bC036834BA66EC8073Ced8c1d9490AD67A3A0bC"
      - PONDER_MARKETPLACE_ADDRESS="0x83c62Cc36B792eE22ba14e74E07Ab05eC2630d1b"
      - PONDER_GENERATIVE_ERC721_ADDRESSES="0xE797f81873F37cAd0607FFD4DfE4155fe452776a"
      - DATABASE_URL=postgresql://postgres:LewzLenIOJQVzHXDGFxnkUyffkkbzwpL@:/railway
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  postgres_data:
